# ------------------------------------------------------------------------------
# inventory/host_vars/prod4/public.yml
# ------------------------------------------------------------------------------

---

wp_subdomain: www
wp_admin_password: "{{ wp_priv_admin_password }}"
wp_database_password: "{{ wp_priv_database_password }}"
wp_reverse_proxy_pass_port: 8082
